CREATE SCHEMA IF NOT EXISTS idler;

CREATE TABLE users
(
    id            bigint generated by default as identity primary key,
    name          varchar(255)        not null,
    email         varchar(255) unique not null,
    password_hash varchar(255)        not null,
    registered_at timestamp           not null,
    visited_at    timestamp           not null
);

