CREATE SCHEMA IF NOT EXISTS idler;

CREATE TABLE users
(
    id            bigint generated by default as identity primary key,
    name          varchar(255)        not null,
    email         varchar(255) unique not null,
    password_hash varchar(255)        not null,
    registered_at timestamp           not null,
    visited_at    timestamp           not null
);

CREATE TABLE dialogs
(
    id             bigint generated by default as identity primary key,
    name           varchar(255) default 'some dialog',
    create_at      timestamp                              not null,
    last_message   timestamp,
    first_user_id  bigint
        constraint fk_first_user unique references users  not null,
    second_user_id bigint
        constraint fk_second_user unique references users not null
)

