CREATE SCHEMA IF NOT EXISTS idler;

CREATE TABLE "user"
(
    id            bigint generated by default as identity primary key,
    name          varchar(255)        not null,
    email         varchar(255) unique not null,
    password_hash varchar(255)        not null,
    registered_at timestamp           not null,
    visited_at    timestamp           not null
);

CREATE TABLE conversation
(
    id           uuid default gen_random_uuid() primary key,
    name         varchar(255)                        not null,
    owner        bigint
        constraint fk_owner unique references "user" not null,
    participants jsonb
);